apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: "$POSTGRES_HOST:$POSTGRES_PORT"
    database: "$POSTGRES_DB"
    user: "$POSTGRES_USER"
    secureJsonData:
      password: "$POSTGRES_PASSWORD"
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: true
    editable: false
